import Head from 'next/head'
import Layout from '../components/layout'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <Layout>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>
          Welcome to ScribeDAO
        </h1>
      </main>
    </Layout>
  )
}

export default Home
