import Head from 'next/head'
import Layout from '../components/layout'

const Home = () => {
  return (
    <Layout>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Welcome to ScribeDAO</h1>
      </main>
    </Layout>
  )
}

export default Home
